export const influencersData = [
  {
    id: "1",
    name: "Jane Doe",
    platform: [
      {
        platform: "Instagram",
        followers: "150k",
        platformLink: "https://www.instagram.com/janedoe",
      },
      {
        platform: "Facebook",
        followers: "2M",
        platformLink: "https://www.facebook.com",
      },
    ],
    location: "New York, USA",
    gender: "Female",
    age: 25,
    price: "₹200",
    star: "4.5",
    ratings: "1219",
    category: "Fashion & Lifestyle Influencer",
    description:
      "Jane Doe is a passionate fashion and lifestyle influencer based in New York. She loves sharing her daily outfits, beauty routines, and lifestyle tips with her followers. With a strong presence on Instagram and Facebook, she inspires thousands to embrace their personal style and confidence.",
    image: "https://randomuser.me/api/portraits/women/44.jpg",
    images: [
      "https://randomuser.me/api/portraits/women/44.jpg",
      "https://randomuser.me/api/portraits/women/45.jpg",
      "https://randomuser.me/api/portraits/women/46.jpg",
    ],
    packages: [
      {
        type: "Story",
        price: "Rs.500/story",
        duration: "24 hours",
        reach: "10K followers",
        engagement: "5%",
      },
      {
        type: "Image",
        price: "Rs.1000/image",
        duration: "Permanent",
        reach: "15K followers",
        engagement: "7%",
      },
      {
        type: "Video",
        price: "Rs.1500/video",
        duration: "Permanent",
        reach: "20K followers",
        engagement: "10%",
      },
    ],
    reviewsData: [
      {
        id: "1",
        user: "Alice Smith",
        rating: 4,
        comment: "Great influencer! Very professional and effective.",
      },
      {
        id: "2",
        user: "Bob Johnson",
        rating: 5,
        comment: "Absolutely amazing experience! Highly recommend.",
      },
      {
        id: "3",
        user: "Charlie Brown",
        rating: 3,
        comment: "Decent influencer, but could improve on communication.",
      },
    ],
  },
  {
    id: "2",
    name: "John Smith",
    platform: [
      {
        platform: "Instagram",
        followers: "120k",
        platformLink: "https://www.instagram.com/johnsmith",
      },
      {
        platform: "YouTube",
        followers: "180k",
        platformLink: "https://www.youtube.com/c/JohnSmith",
      },
      {
        platform: "Facebook",
        followers: "300k",
        platformLink: "https://www.facebook.com/johnsmith",
      },
    ],
    location: "Los Angeles, USA",
    gender: "Male",
    age: 28,
    price: "₹1800",
    star: "4.7",
    ratings: "119",
    category: "Tech Reviewer & Vlogger",
    description:
      "John Smith is a tech enthusiast who enjoys reviewing the latest gadgets and sharing his insights with his audience. His YouTube channel is filled with in-depth reviews, unboxings, and vlogs that cover everything from smartphones to gaming gear. He connects with tech lovers on multiple platforms and offers honest opinions on products.",
    image: "https://randomuser.me/api/portraits/men/34.jpg",
    images: [
      "https://randomuser.me/api/portraits/men/34.jpg",
      "https://randomuser.me/api/portraits/men/35.jpg",
      "https://randomuser.me/api/portraits/men/36.jpg",
    ],
    packages: [
      {
        type: "Story",
        price: "Rs.500/story",
        duration: "24 hours",
        reach: "10K followers",
        engagement: "5%",
      },
      {
        type: "Image",
        price: "Rs.1000/image",
        duration: "Permanent",
        reach: "15K followers",
        engagement: "7%",
      },
      {
        type: "Video",
        price: "Rs.1500/video",
        duration: "Permanent",
        reach: "20K followers",
        engagement: "10%",
      },
    ],
    reviewsData: [
      {
        id: "1",
        user: "Alice Smith",
        rating: 4,
        comment: "Great influencer! Very professional and effective.",
      },
      {
        id: "2",
        user: "Bob Johnson",
        rating: 5,
        comment: "Absolutely amazing experience! Highly recommend.",
      },
      {
        id: "3",
        user: "Charlie Brown",
        rating: 3,
        comment: "Decent influencer, but could improve on communication.",
      },
    ],
  },
  {
    id: "3",
    name: "Emily Johnson",
    platform: [
      {
        platform: "Facebook",
        followers: "80k",
        platformLink: "https://www.facebook.com/emilyjohnson",
      },
      {
        platform: "Instagram",
        followers: "110k",
        platformLink: "https://www.instagram.com/emilyjohnson",
      },
    ],
    location: "London, UK",
    gender: "Female",
    age: 30,
    price: "₹2800",
    star: "3.7",
    ratings: "319",
    category: "Health & Wellness Coach",
    description:
      "Emily Johnson is a dedicated health and wellness coach from London, helping her audience achieve their fitness and mental health goals. She provides valuable insights on maintaining a balanced lifestyle, from nutrition to workout tips. Her social media channels are a source of motivation for those seeking to improve their well-being.",
    image: "https://randomuser.me/api/portraits/women/47.jpg",
    images: [
      "https://randomuser.me/api/portraits/women/47.jpg",
      "https://randomuser.me/api/portraits/women/48.jpg",
      "https://randomuser.me/api/portraits/women/49.jpg",
    ],
    packages: [
      { type: "Story", price: "Rs.150/story" },
      { type: "Image", price: "Rs.300/image" },
      { type: "Video", price: "Rs.500/video" },
    ],
  },
  {
    id: "4",
    name: "Michael Lee",
    platform: [
      {
        platform: "Instagram",
        followers: "150k",
        platformLink: "https://www.instagram.com/michaellee",
      },
      {
        platform: "Twitter",
        followers: "50k",
        platformLink: "https://twitter.com/michaellee",
      },
    ],
    location: "San Francisco, USA",
    gender: "Male",
    age: 27,
    price: "₹400",
    star: "4.9",
    ratings: "5319",
    category: "Tech Enthusiast & Reviewer",
    description:
      "Michael Lee is a San Francisco-based tech enthusiast with a knack for breaking down complex technology into digestible content for his audience. His followers rely on him for detailed reviews, how-tos, and tech news. Whether it’s the latest smartphone or a software update, Michael is always ahead of the curve.",
    image: "https://randomuser.me/api/portraits/men/37.jpg",
    images: [
      "https://randomuser.me/api/portraits/men/37.jpg",
      "https://randomuser.me/api/portraits/men/38.jpg",
      "https://randomuser.me/api/portraits/men/39.jpg",
    ],
    packages: [
      {
        type: "Story",
        price: "Rs.500/story",
        duration: "24 hours",
        reach: "10K followers",
        engagement: "5%",
      },
      {
        type: "Image",
        price: "Rs.1000/image",
        duration: "Permanent",
        reach: "15K followers",
        engagement: "7%",
      },
      {
        type: "Video",
        price: "Rs.1500/video",
        duration: "Permanent",
        reach: "20K followers",
        engagement: "10%",
      },
      {
        type: "Others",
        price: "Rs.1500-Rs.6000",
        duration: "Permanent",
        reach: "20K followers",
        engagement: "10%",
      },
    ],
    reviewsData: [
      {
        id: "1",
        user: "Alice Smith",
        rating: 4,
        comment: "Great influencer! Very professional and effective.",
      },
      {
        id: "2",
        user: "Bob Johnson",
        rating: 5,
        comment: "Absolutely amazing experience! Highly recommend.",
      },
      {
        id: "3",
        user: "Charlie Brown",
        rating: 3,
        comment: "Decent influencer, but could improve on communication.",
      },
    ],
  },
  {
    id: "5",
    name: "Sarah Brown",
    platform: [
      {
        platform: "YouTube",
        followers: "500k",
        platformLink: "https://www.tiktok.com/@sarahbrown",
      },
      {
        platform: "Instagram",
        followers: "300k",
        platformLink: "https://www.instagram.com/sarahbrown",
      },
    ],
    location: "Miami, USA",
    gender: "Female",
    age: 22,
    price: "₹800",
    star: "4.2",
    ratings: "119",
    category: "Dance & Music Creator",
    description:
      "Sarah Brown is a young and vibrant dance and music creator from Miami. Her content on TikTok and Instagram features creative choreography and catchy tunes that resonate with her audience. Sarah’s passion for performing arts has led her to build a strong community of followers who enjoy her energetic and fun-filled posts.",
    image: "https://randomuser.me/api/portraits/women/50.jpg",
    images: [
      "https://randomuser.me/api/portraits/women/50.jpg",
      "https://randomuser.me/api/portraits/women/51.jpg",
      "https://randomuser.me/api/portraits/women/52.jpg",
    ],
    packages: [
      {
        type: "Story",
        price: "Rs.500/story",
        duration: "24 hours",
        reach: "10K followers",
        engagement: "5%",
      },
      {
        type: "Image",
        price: "Rs.1000/image",
        duration: "Permanent",
        reach: "15K followers",
        engagement: "7%",
      },
      {
        type: "Video",
        price: "Rs.1500/video",
        duration: "Permanent",
        reach: "20K followers",
        engagement: "10%",
      },
      {
        type: "Others",
        price: "Rs.1500-Rs.6000",
        duration: "Permanent",
        reach: "20K followers",
        engagement: "10%",
      },
    ],
    reviewsData: [
      {
        id: "1",
        user: "Alice Smith",
        rating: 4,
        comment: "Great influencer! Very professional and effective.",
      },
      {
        id: "2",
        user: "Bob Johnson",
        rating: 5,
        comment: "Absolutely amazing experience! Highly recommend.",
      },
      {
        id: "3",
        user: "Charlie Brown",
        rating: 3,
        comment: "Decent influencer, but could improve on communication.",
      },
    ],
  },
];
