"use client";
import React, { useState } from "react";
import {
  Box,
  Typography,
  TextField,
  Button,
  Card,
  CardContent,
  Grid,
  Snackbar,
  Alert,
} from "@mui/material";
import { styled } from "@mui/material/styles";
import { useRouter } from "next/navigation";
import axios from "axios";
import { BaseUrl } from "@/common/utils";
import { useAppDispatch } from "@/lib/hooks";
import { paymentStatus } from "@/lib/features/Payments/paymentSlice";

const StyledBox = styled(Box)(({ theme }) => ({
  padding: theme.spacing(3),
  maxWidth: 600,
  margin: "auto",
  [theme.breakpoints.down("sm")]: {
    padding: theme.spacing(2),
  },
}));

const PaymentCard = styled(Card)(({ theme }) => ({
  marginTop: theme.spacing(3),
  boxShadow: theme.shadows[5],
}));

const PaymentPage: React.FC = ({ searchParams }) => {
  const router = useRouter();
  const dispatch = useAppDispatch();
  const [amount, setAmount] = useState<string>("");
  const [cardNumber, setCardNumber] = useState<string>("");
  const [expiryDate, setExpiryDate] = useState<string>("");
  const [cvv, setCvv] = useState<string>("");
  const [snackbarOpen, setSnackbarOpen] = useState<boolean>(false);
  const [snackbarMessage, setSnackbarMessage] = useState<string>("");
  const _id = searchParams._id;

  const handleSubmit = async () => {
    // Implement payment processing logic here
    console.log({ amount, cardNumber, expiryDate, cvv });

    // Show success message
    setSnackbarMessage("Payment successful!");
    setSnackbarOpen(true);

    // Reset fields after submission
    setAmount("");
    setCardNumber("");
    setExpiryDate("");
    setCvv("");
    try {
      const newStatus = "Payment Completed";
      await axios
        .put(`${BaseUrl}/api/changeStatus`, { _id, newStatus })
        .then((res) => {
          if (res.status === 200) {
            dispatch(paymentStatus(true));
            router.push("orders");
          }
        })
        .catch((err) => console.log("Err", err));
    } catch (error) {
      console.error("Error approving order:", error);
    }
    // router?.push("router");
    //redirect back and change the status
  };

  const handlePayment = async () => {
    try {
      const response = await axios.post(`${BaseUrl}/api/createPayment`, {
        amount,
        orderId: _id, // Unique order ID
      });

      const { data } = response;

      // Initialize Paytm payment
      const paytmParams = {
        MID: "YOUR_MERCHANT_ID", // Replace with your Merchant ID
        ORDERID: data.orderId, // Order ID generated by your server
        CUSTID: "YOUR_CUSTOMER_ID", // Customer ID
        CHANNELID: "WAP", // Channel ID
        INDUSTRY_TYPE_ID: "Retail", // Industry type ID
        CALLBACK_URL: "YOUR_CALLBACK_URL", // Your callback URL
        TXNAMOUNT: amount,
        CHECKSUMHASH: data.checksum, // Checksum generated by your server
      };

      const paytmURL = "https://securegw.paytm.in/order/process"; // Paytm payment URL

      // Open Paytm payment page
      const form = document.createElement("form");
      form.method = "POST";
      form.action = paytmURL;

      Object.keys(paytmParams).forEach((key) => {
        const input = document.createElement("input");
        input.type = "hidden";
        input.name = key;
        input.value = paytmParams[key];
        form.appendChild(input);
      });

      document.body.appendChild(form);
      form.submit();

      // Show success message
      setSnackbarMessage("Payment initiated!");
      setSnackbarOpen(true);
    } catch (error) {
      console.error("Payment error:", error);
      setSnackbarMessage("Payment failed. Please try again.");
      setSnackbarOpen(true);
    }
  };

  return (
    <StyledBox>
      <Typography variant="h4" gutterBottom>
        Payment Page
      </Typography>

      <PaymentCard>
        <CardContent>
          <Typography variant="h6" gutterBottom>
            Enter Payment Details
          </Typography>

          <TextField
            fullWidth
            label="Amount"
            variant="outlined"
            value={amount}
            onChange={(e) => setAmount(e.target.value)}
            margin="normal"
            type="number"
          />
          <TextField
            fullWidth
            label="Card Number"
            variant="outlined"
            value={cardNumber}
            onChange={(e) => setCardNumber(e.target.value)}
            margin="normal"
            type="text"
          />
          <Grid container spacing={2}>
            <Grid item xs={6}>
              <TextField
                fullWidth
                label="Expiry Date (MM/YY)"
                variant="outlined"
                value={expiryDate}
                onChange={(e) => setExpiryDate(e.target.value)}
                margin="normal"
                type="text"
              />
            </Grid>
            <Grid item xs={6}>
              <TextField
                fullWidth
                label="CVV"
                variant="outlined"
                value={cvv}
                onChange={(e) => setCvv(e.target.value)}
                margin="normal"
                type="password"
              />
            </Grid>
          </Grid>

          <Button
            variant="contained"
            color="primary"
            onClick={handleSubmit}
            fullWidth
            sx={{ marginTop: 2 }}
          >
            Pay Now
          </Button>
        </CardContent>
      </PaymentCard>

      <Snackbar
        open={snackbarOpen}
        autoHideDuration={3000}
        onClose={() => setSnackbarOpen(false)}
      >
        <Alert onClose={() => setSnackbarOpen(false)} severity="success">
          {snackbarMessage}
        </Alert>
      </Snackbar>
    </StyledBox>
  );
};

export default PaymentPage;
